Repository kpatterson01/step-capstone-2020, pull requests merged in 2020-07, with the labels that each got.

#20 Resource Provisioning Metrics
  resource_metric_logic_test.py
  resource_provisioning.py
Labels: enhancement

#21 Add usage similarity function and test cases
  company.py
  company_test.py
  employee.py
  employee_test.py
  main.py
  resource.py
  utilities/employee_resource_map.py
  utilities/resource_map_creator.py
Labels: super enhancement

#23 Taken from Kayla's PR - reorganizing file structure
  app.py
  core/__init__.py
  core/company.py
  core/company_test.py
  core/employee.py
  core/employee_resource_map.py
  core/main.py
  core/resource.py
  core/resource_metric_logic_test.py
  core/resource_provisioning.py
  core/utilities/__init__.py
  core/utilities/access_normalization.py
  core/utilities/data_exploration.ipynb
  core/utilities/distance_validation.py
  core/utilities/distance_validation_test.py
  core/utilities/normalizing_data.py
  core/utilities/normalizing_data_test.py
  core/utilities/resource_analysis.py
  core/utilities/resource_map_creator.py
  core/utilities/usage_sort.py
  core/utilities/usage_sort_test.py
  core/utilities/user_resource_map.py
  utilities/.ipynb_checkpoints/data_exploration-checkpoint.ipynb
  views/index.html
  views/script.js
  views/style.css
Labels: duplicate

#24 Add max depth of company function to Company class
  core/company.py
  core/company_test.py
  core/main.py
  core/resource_provisioning.py
  core/utilities/regression.ipynb
  setup.sh
Labels: slight glow up

#25 Add cover page of website.
  app.py
  static/style.css
  templates/index.html
  templates/research.html
  views/index.html
  views/script.js
  views/style.css
Labels: slight glow up

#27 Added section in main.py to read employee resources from JSON
  core/employee_resource_map.py
  core/main.py
Labels: fix

#32 Add provision pie charts and dark mode feature.
  static/darkMode.css
  static/darkMode.js
  static/metricStyle.css
  static/pieScript.js
  templates/hierachyTree.html
  templates/provisionMetrics.html
Labels: super enhancement

#35 Utility update
  core/parsing/rule.py
  core/parsing/syntax_tree.py
  core/resource_provisioning.py
  core/rule.py
  core/utilities/mini_table_creator.py
Labels: enhancement, fix, slight glow up
