Repository kpatterson01/step-capstone-2020, pull requests merged in 2020-08, with the labels that each got.

#42 Add pathway highlight and selection of nodes.
  static/treeScript.js
  static/treeStyle.css
  templates/hierachyTree.html
Labels: major glow up

#45 Refactor usage similarity, add CEO to company class, add correlation analysis
  app.py
  app.yaml
  core/company.py
  core/company_test.py
  core/employee.py
  core/resource.py
  core/sample.py
  core/usage_similarity.py
  core/utilities/correlation_analysis.ipynb
  core/utilities/distance_validation.py
  core/utilities/regression.ipynb
  core/utilities/trim_data.py
  static/pieScript.js
  static/treeScript.js
Labels: take me home country roads, updates

#44 Add attribute clustering notebook
  core/attribute_clustering_analysis.ipynb
Labels: take me home country roads

#46 Add team page and uncollapsible feature on tree.
  app.py
  static/images/dean.png
  static/images/kayla.jpg
  static/images/tedi.jpg
  static/team.css
  static/treeScript.js
  templates/index.html
  templates/research.html
  templates/team.html
Labels: take me home country roads
